export const languageMap: { [key: string]: string } = {
  javascript: "javascript",
  typescript: "typescript",
  python: "python",
  go: "go",
  rust: "rust",
  java: "java",
  cpp: "cpp",
  c: "c",
  csharp: "csharp",
  php: "php",
  ruby: "ruby",
  swift: "swift",
  kotlin: "kotlin",
  html: "html",
  css: "css",
  json: "json",
  sql: "sql",
  yaml: "yaml",
};

export const defaultCode: { [key: string]: string } = {
  javascript: 'console.log("Hello, Livecode!");',
  typescript: 'const message: string = "Hello, Livecode!";\nconsole.log(message);',
  python: 'print("Hello, Livecode!")',
  go: 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, Livecode!")\n}',
  rust: 'fn main() {\n    println!("Hello, Livecode!");\n}',
  java: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, Livecode!");\n    }\n}',
  cpp: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, Livecode!" << std::endl;\n    return 0;\n}',
  c: '#include <stdio.h>\n\nint main() {\n    printf("Hello, Livecode!\\n");\n    return 0;\n}',
  csharp: 'using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("Hello, Livecode!");\n    }\n}',
  php: '<?php\necho "Hello, Livecode!";\n?>',
  ruby: 'puts "Hello, Livecode!"',
  swift: 'import Foundation\n\nprint("Hello, Livecode!")',
  kotlin: 'fun main() {\n    println("Hello, Livecode!")\n}',
  html: '<!DOCTYPE html>\n<html>\n<head>\n    <title>Livecode</title>\n</head>\n<body>\n    <h1>Hello, Livecode!</h1>\n</body>\n</html>',
  css: 'body {\n    font-family: sans-serif;\n    background: #f0f0f0;\n    color: #333;\n}',
  json: '{\n  "message": "Hello, Livecode!",\n  "version": "1.0.0"\n}',
  sql: 'SELECT * FROM users WHERE name = "Livecode";',
  yaml: 'message: Hello, Livecode!\nversion: 1.0.0',
};
