export const darkTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "e4e4e7", background: "0d0d0d" },
    { token: "comment", foreground: "7c7c7c", fontStyle: "italic" },
    { token: "constant", foreground: "f59e42" },
    { token: "string", foreground: "a3e635" },
    { token: "keyword", foreground: "8b5cf6" },
    { token: "number", foreground: "ef4444" },
    { token: "type", foreground: "06b6d4" },
    { token: "variable", foreground: "eab308" },
    { token: "function", foreground: "22d3ee" },
    { token: "class", foreground: "f472b6" },
    { token: "interface", foreground: "f87171" },
    { token: "parameter", foreground: "facc15" },
    { token: "delimiter", foreground: "a1a1aa" },
  ],
  colors: {
    "editor.background": "#0d0d0d",
    "editor.foreground": "#e4e4e7",
    "editorLineNumber.foreground": "#52525b",
    "editorLineNumber.activeForeground": "#a1a1aa",
    "editor.selectionBackground": "#6366f133",
    "editor.inactiveSelectionBackground": "#6366f11a",
    "editorCursor.foreground": "#6366f1",
    "editor.lineHighlightBackground": "#18181b",
    "editorWidget.background": "#18181b",
    "editorWidget.border": "#27272a",
    "editorSuggestWidget.background": "#18181b",
    "editorSuggestWidget.border": "#27272a",
    "editorSuggestWidget.selectedBackground": "#27272a",
    "list.hoverBackground": "#27272a",
    "list.activeSelectionBackground": "#6366f133",
    "list.inactiveSelectionBackground": "#27272a",
    "editorSuggestWidget.foreground": "#e4e4e7",
    "editorSuggestWidget.highlightForeground": "#6366f1",
    "editorBracketMatch.background": "#363636ff",
    "editorBracketMatch.border": "#6366f1",
    "editorIndentGuide.background": "#27272a",
    "editorIndentGuide.activeBackground": "#6366f1",
  },
};

// Monaco Editor custom light theme with improved syntax highlighting
export const lightTheme = {
  base: "vs" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "09090b", background: "ffffff" },
    { token: "comment", foreground: "78716c", fontStyle: "italic" },
    { token: "constant", foreground: "d97706" },
    { token: "string", foreground: "22c55e" },
    { token: "keyword", foreground: "7c3aed" },
    { token: "number", foreground: "dc2626" },
    { token: "type", foreground: "0ea5e9" },
    { token: "variable", foreground: "ca8a04" },
    { token: "function", foreground: "06b6d4" },
    { token: "class", foreground: "db2777" },
    { token: "interface", foreground: "b91c1c" },
    { token: "parameter", foreground: "eab308" },
    { token: "delimiter", foreground: "a1a1aa" },
  ],
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#09090b",
    "editorLineNumber.foreground": "#a1a1aa",
    "editorLineNumber.activeForeground": "#52525b",
    "editor.selectionBackground": "#6366f133",
    "editor.inactiveSelectionBackground": "#6366f11a",
    "editorCursor.foreground": "#6366f1",
    "editor.lineHighlightBackground": "#fafafa",
    "editorWidget.background": "#ffffff",
    "editorWidget.border": "#e4e4e7",
    "editorSuggestWidget.background": "#ffffff",
    "editorSuggestWidget.border": "#e4e4e7",
    "editorSuggestWidget.selectedBackground": "#f4f4f5",
    "list.hoverBackground": "#f4f4f5",
    "list.activeSelectionBackground": "#6366f133",
    "list.inactiveSelectionBackground": "#f4f4f5",
    "editorSuggestWidget.foreground": "#09090b",
    "editorSuggestWidget.highlightForeground": "#6366f1",
    "editorBracketMatch.background": "#eeeeee",
    "editorBracketMatch.border": "#6366f1",
    "editorIndentGuide.background": "#e4e4e7",
    "editorIndentGuide.activeBackground": "#6366f1",
  },
};
